### ISSUE TITLE
Footer >> Padrão

### ISSUE THREAD

**Issue by diogosp** [brasadesign/mb45-theme#1]
Footer Padrão para todo o site:

![2016-08-09_18h47_38](https://cloud.githubusercontent.com/assets/5107285/17534914/0c8c1874-5e62-11e6-84e8-21115b0b74fd.png)

https://drive.google.com/open?id=0B7wXMgHIJOr-ZDhzdVgwTmQ1MUU

**Comment by diogosp** [comment]
@isaquemelo @matheusgimenez como eu edito o Rodapé? ele não está como MENU lá no WP.

**Comment by isaquemelo** [comment]
Ele ficou da mesma forma do boa terra. Appearance > Widgets > Footer 1,2,3,4

**Comment by diogosp** [comment]
@isaquemelo valeu. como eu altero o TIPO de Footer/Widget? no Mapa (Footer 3) queria que puxasse um código ao invés de Menu. (como Footer4)

**Comment by isaquemelo** [comment]
Simples pcro... apaga o widget atual (que tá um CUSTOM MENU), "abre" o widget e aperta delete... dps adiciona um novo widget do tipo TEXT. No content pode meter codigo. :D

**Comment by isaquemelo** [comment]
@diogosp essa aqui deu certo?

**Comment by diogosp** [comment]
Sim!!!

**Comment by diogosp** [comment]
@matheusgimenez o rodapé não está aparecendo. Sumiu.

**Comment by isaquemelo** [comment]
Feito.
