### ISSUE TITLE
Serviço de SMS - PLIVO

### ISSUE THREAD

**Issue by diogosp** [brasadesign/mb45-theme#18]
Este serviço já está integrado com o Woo e com o plugin de Agendamento.
Será nossa opção de Serviço pra enviar SMS de confirmação com o código da compra.

https://www.twilio.com/

**Comment by diogosp** [comment]
Plugin instalado no DEV.
Falta dados para testar a integração

**Comment by diogosp** [comment]
@matheusgimenez API testada (tanto no DEV quanto em PROD).
Agora falta o campo no STEP2 para resolvermos isto definitivamente. 
Campo onde a pessoa confirma querer receber o agendamento por SMS

**Comment by matheusgimenez** [comment]
Feito. Está no master (dev.brasa).

**Comment by LuwkasLima** [comment]
Atualizando com o que foi discutido hoje:

1 - O SMS parece ter um delay que nao esta muito legal, mas isso acontece com celulares do BR. ACAO: Fazer um teste com celulares dos EUA (Lucas)
2 - Descobrimos que precisamos colocar o Country/Area Code antes do celular, e dessa forma, o SMS ira funcionar.  Parece que a API permite que seja feito uma modificacao no numero antes de enviar a requisicao ao PLIVIO, portanto, a solucao encontrada foi verificar se o numero de telefone inserido pelo usuario possui o 1, em caso negativo, incluir o 1 na frente.
_O Lucas testou sem o 1 na frente e nao funcionou._

**Comment by diogosp** [comment]
Testei sem o +55 tb.. não rolou também.

@matheusgimenez seguir com o plano de preencher pro usuário caso ele não tenha feito

**Comment by matheusgimenez** [comment]
Resolvido. Está na produção (tive que enviar para podermos testar, ja que o dev.brasa ta dando probleminha com o SMS).

**Comment by LuwkasLima** [comment]
Funcionou legal com o Appointment e o @matheusgimenez testou com o Gift Card. Agora temos 2 mensagens diferentes pra cada um com os dados relevantes.
