### ISSUE TITLE
Gift Card

### ISSUE THREAD

**Issue by diogosp** [brasadesign/mb45-theme#19]
Plugin
https://br.wordpress.org/plugins/yith-woocommerce-gift-cards/screenshots/

**Comment by diogosp** [comment]
@matheusgimenez @isaquemelo Eu vi o andamento da página do Produto

<img width="1632" alt="screen shot 2017-01-26 at 13 39 38" src="https://cloud.githubusercontent.com/assets/5107285/22337825/0dd69b28-e3cd-11e6-88f6-3fefc398a354.png">

O que precisamos:

- [ ] Colocar o produto no fluxo de compra igual ao Agendamento. Isto é ao invés de "Proceed to Cart" colocar o botão NEXT (depois que seleciona o valor do Gift). e aí vai pro STEP2 e STEP3 já construídos.

- [ ] Remover aquelas mensagens de VIEW CART... etc..

**Comment by isaquemelo** [comment]
@diogosp @diogosp não acho certo removermos estas mensagens haja vista que são de extrema importância para o UX, além de que essa é a única forma do usuário saber o que fazer após adicionar ao carrinho o produto

**Comment by LuwkasLima** [comment]
@diogosp identificamos que o plugin eh tao simples que possui alguns inconvenientes que eu vou documentar aqui e talvez sua tarefa seja ter certeza que a cliente compra a ideia, porque ter que refazer isso vai ser muitas horas, entao pode ser uma briga boa.

**1 - Gift Card comprado cria uma Order que nao eh COMFIRMADO (Comfirmed) automaticamente:**
Descobrimos que quando compramos um gift card, ele nao eh automaticamente colocado como confirmed e portanto alguem tem que manualmente clicar em Confirm pra ele enviar o e-mail (e SMS) com o codigo do gift card.

**2 - Gift Card eh enviado de forma muito ruim, escondido no meio do template default de order:**

![image](https://cloud.githubusercontent.com/assets/5949986/22843971/8768920e-efa1-11e6-8925-f6e19af2eecc.png)

O problema aqui eh que nesse process, o cliente ja recebeu 1 e-mail anteriormente falando que a ordem dele estava sendo processada. Dai ele recebe mais um e-mail com o mesmo layout dizendo que a ordem foi CONFIRMADA e no meio da linha de produto aparece o codigo do gift card. Nao vai ser legal isso...

De resto, testamos tudo e esta funcionando.

**Comment by diogosp** [comment]
@isaquemelo @matheusgimenez a cliente só pediu este pente fino aqui:

- ajustar o botão do Gift pra ficar no mesmo estilo do checkout

Depois disso vai pro ar (ainda não sei onde elas vão colocar no menu).

**Comment by isaquemelo** [comment]
Feito.

**Comment by diogosp** [comment]
@LuwkasLima pra te responder sobre o Gift e suas limitações.
Sim eu expliquei pra cliente que fizemos a versão FREE do plugin que eram as horas que estavam contabilizadas. Apresentei a versão paga que tem dezenas de opções novas (inclusive enviar o código de outras formas etc).

Sobre a confirmação de pagamento. Sim o código só pode ir quando o pagamento estiver feito e a compra COMPLETA. não tem sentido enviar antes do fechamento disso. seria uma falha.

**Comment by LuwkasLima** [comment]
Perfect!
