### ISSUE TITLE
Header >> Padrão

### ISSUE THREAD

**Issue by diogosp** [brasadesign/mb45-theme#2]
Header Padrão do site.
- [ ] header fixo.
- [ ] Transparente

HOME
![2016-08-09_18h50_14](https://cloud.githubusercontent.com/assets/5107285/17534952/4199a680-5e62-11e6-8dc5-c28b69664c95.png)

Página Menu
![2016-08-09_18h51_41](https://cloud.githubusercontent.com/assets/5107285/17534970/53665e08-5e62-11e6-88d8-f881f08e5079.png)

Página Looks
![2016-08-09_18h52_33](https://cloud.githubusercontent.com/assets/5107285/17534997/7df1dd64-5e62-11e6-88d7-dd9053cd76de.png)

https://drive.google.com/open?id=0B7wXMgHIJOr-S0xGSDRrQWFUanM

**Comment by diogosp** [comment]
@isaquemelo @matheusgimenez 
- O Menu superior é TRANSPARENTE.
- Vejam também como os sub-menus se comportam (eles precisam aparecer logo abaixo do menu principal
- precisa Diminuir a Altura da faixa do Menu. No layout ele aparece bem mais fininho.

**Comment by isaquemelo** [comment]
1 -  Vou deixar transparente. Entretanto, surgirão problemas relacionados a visualização do menu.
3 -  Como assim? Se ele vai ficar transparente não vai existir faixa, então, como deixarei menor se não será notado. Cita que faixa é essa.. please.
DEV:
![dev](https://cloud.githubusercontent.com/assets/7103838/19361229/2fa7d310-9158-11e6-9239-c24612772dbe.PNG)
LAYOUT:
![layout](https://cloud.githubusercontent.com/assets/7103838/19361230/2fab9716-9158-11e6-89a5-f6193ca51a39.PNG)
[a diferença da altura do texto central(MANICURE + BLOWOUT 45 MINUTES) se dá devido a diferença de height entre a minha tela e a resolução utilizada na criação do design]
Não entendo essa tal faixa diferente :(

**Comment by isaquemelo** [comment]
Problemas citados acima relacionados à visualização: 
![capturar](https://cloud.githubusercontent.com/assets/7103838/19363286/4383e6b4-9160-11e6-9931-4ab16d237ee3.PNG)

**Comment by isaquemelo** [comment]
Resultado SUBMENU (ver design pagina hair):
DESKTOP:
![desk](https://cloud.githubusercontent.com/assets/7103838/19364756/d34fa530-9165-11e6-85c8-94e48680ca3c.PNG)

MOBILE:
![mobile](https://cloud.githubusercontent.com/assets/7103838/19364792/fe0e7d1e-9165-11e6-8493-0ceb5d40999a.PNG)

**Comment by diogosp** [comment]
@isaquemelo 
Deixa tudo transparente. Caso houvesse uma solução intermediária eu proporia assim: cada slide (página) tendo um controle de transparencia (tipo 100% - 50% 20%) o que acha?

outra coisa, vc só aplicou a transparencia no primeiro slide da Home. tem que ser pra todos

**Comment by isaquemelo** [comment]
1 - @diogosp vai ter que ver isso com o @matheusgimenez, ele tem que meter um backend.. Se eu aplicar transparência na geral não vai dar pra ver nada(só vai dar pra ver nas paginas escuras). Você acha melhor eu desabilitar mesmo(deixar tudo transparente) ou é melhor esperar pelo Matheus para fazer o trabalho completo? Mas que fique claro que se eu deixar transparente a visualização será afetada.
2 - Aguardo resposta do ultimo tópico em relação a altura da faixa.

**Comment by diogosp** [comment]
@isaquemelo 

Sobre o ponto 2 - se por ventura tivermos que usar algo mais opaco ao invés de totalmente transparente teremos que mexer nesta largura.

sim. Deixa tudo transparente. Pra eu mostrar pra cliente do jeito que ela quer.

**Comment by isaquemelo** [comment]
@diogosp O farei amanhã durante a tarde.

**Comment by isaquemelo** [comment]
@diogosp agora todos os headers do site estão transparentes.

**Comment by diogosp** [comment]
@isaquemelo 
Alteração no MENU:

- [ ] alterar a magin-left, pra ficar mais alinhado pra direita

Ver screen:

<img width="1280" alt="screen shot 2016-10-21 at 9 31 36 pm 2x" src="https://cloud.githubusercontent.com/assets/5107285/21826646/76478f06-d76f-11e6-8924-c794007b2dc1.png">

**Comment by diogosp** [comment]
Só pra confirmar, são todos os elementos

**Comment by isaquemelo** [comment]
Feito.
