### ISSUE TITLE
BUG - erro ao criar usuário na produção

### ISSUE THREAD

**Issue by diogosp** [brasadesign/mb45-theme#20]
Matheus, to tentando criar novos usuários no MB45 e dá este erro aqui
@matheusgimenez 

Fatal error: Class 'WC_Widget' not found in /home/biacastro16/public_html/wp-content/themes/mb45-theme/inc/custom-widgets.php on line 18

**Comment by diogosp** [comment]
@matheusgimenez ainda persiste o erro.
Ele manda mensagem pra ativação corretamente, mas depois ao clicar pra ativar ele não abre o link pra concluir da erro 500
Ninguém está conseguindo criar o usuário OU alterar o email padrão de admin do site (que agora pede uma confirmação via email tb)


<img width="1367" alt="screen shot 2017-01-12 at 13 17 15" src="https://cloud.githubusercontent.com/assets/5107285/21895379/ada984d0-d8c9-11e6-8663-aa1e99b9400f.png">

<img width="1430" alt="screen shot 2017-01-12 at 13 19 06" src="https://cloud.githubusercontent.com/assets/5107285/21895393/b7ba9e00-d8c9-11e6-9325-9dab569a7740.png">

**Comment by matheusgimenez** [comment]
Isso aqui ja foi resolvido?

**Comment by diogosp** [comment]
@matheusgimenez Já

**Comment by diogosp** [comment]
@matheusgimenez eram duas coisas aqui, uma foi corrigida. 
Mas a de mandar o email de confirmação pra altera o ADMIN não está funfando não.
Elas nao recebem o email

**Comment by diogosp** [comment]
@matheusgimenez 
bom, elas não receberam e-mail mesmo. é Google Apps que usam lá.
Já alterou manualmente, ok.
Porém isto pode ser um problema pra resolver posteriormente.

**Comment by diogosp** [comment]
@matheusgimenez voltamos ao erro. nenhum user recebe email de confirmação de criação. (com o link pra ativar a conta)....
