### ISSUE TITLE
slides da Home aumentar column de 8 pra 12

### ISSUE THREAD

**Issue by diogosp** [brasadesign/mb45-theme#26]
A cliente quer uma modificação na Home. @isaquemelo 

Está assim agora:
![unnamed 2](https://cloud.githubusercontent.com/assets/5107285/22163639/bf93e2d6-df3a-11e6-8ed5-80f9d5ae0812.png)

Ela quer com 12, pra ficar assim:
![unnamed 1](https://cloud.githubusercontent.com/assets/5107285/22163649/cbb11156-df3a-11e6-9078-248c6f6e7be7.png)

**Comment by isaquemelo** [comment]
Correção efetuada.

**Comment by diogosp** [comment]
Obrigado Isaque!

**Comment by diogosp** [comment]
@isaquemelo @matheusgimenez  pode subir pra PROD.
