### ISSUE TITLE
ERRO - Step 1 - Calendário só puxando até 16:00

### ISSUE THREAD

**Issue by diogosp** [brasadesign/mb45-theme#27]
@matheusgimenez @isaquemelo quando puxa as horas de possíveis agendamentos só está puxando até as 16h.... Precisamos que puxe até as 20h00 (ou que fique aberto pra puxar todas as horas configuráveis internamente). Isso não pode ser uma restrição.

<img width="1164" alt="screen shot 2017-01-20 at 23 42 52" src="https://cloud.githubusercontent.com/assets/5107285/22170850/7da95b6e-df6a-11e6-8d68-8184bc8031f1.png">

**Comment by matheusgimenez** [comment]
@diogosp Feito.
