### ISSUE TITLE
Remover coluna com link do produto appointment dentro de My Orders (My Account)

### ISSUE THREAD

**Issue by matheusgimenez** [brasadesign/mb45-theme#28]
Screenshot do erro:

![index](https://cloud.githubusercontent.com/assets/4724804/22663514/04f21436-ec94-11e6-92d2-d0a09e78ee0f.png)

Quando clica em appointment vai pro produto (single-product feiona). Penso que a solução pra isso é remover essa coluna inteira, já que só temos um tipo de produto appointment.

O que acha da solução @diogosp ?

To marcando aqui pra eu mesmo fazer no proximo sprint.

**Comment by diogosp** [comment]
me explica a necessidade. e se no futuro elas precisarem de mais produtos appointmente?

**Comment by matheusgimenez** [comment]
@diogosp primeiro, ta repetitivo, varias tabelas com o mesmo valor nessa coluna. Segundo: se o cara clica ali vai pra single product de appointment que nao fizemos o single.

**Comment by diogosp** [comment]
OK. manda BRASA

**Comment by matheusgimenez** [comment]
Feito! Está no master (dev.brasa)
