### ISSUE TITLE
Bug - Sync Appointments com Google Calendar

### ISSUE THREAD

**Issue by diogosp** [brasadesign/mb45-theme#29]
@matheusgimenez 
Só consigo o SYNC 1-way. do website pra Agenda.
O contrário nao funciona e precisa obrigatoriamente.

99% de chance de ser o plugin desatualizado.

**Comment by matheusgimenez** [comment]
Já foi resolvido em produção. 

Aparentemente existe um pequeno de delay, algo como 15minutos.
