### ISSUE TITLE
Home >> Slider Principal

### ISSUE THREAD

**Issue by diogosp** [brasadesign/mb45-theme#3]
Slider Principal da HOME.

Características:
- Imagem de Fundo
- Inserir títulos e sub-títulos
- Inserir Botões de Ação
- Slide com formulário (nós devemos escolher aqui internamente qual form)

![2016-08-09_18h56_38](https://cloud.githubusercontent.com/assets/5107285/17535141/3cff9980-5e63-11e6-928b-d112aabb5b4f.png)
![2016-08-09_18h57_23](https://cloud.githubusercontent.com/assets/5107285/17535143/3deea714-5e63-11e6-9a81-06a1755fc075.png)
![2016-08-09_18h57_39](https://cloud.githubusercontent.com/assets/5107285/17535145/3f7a912e-5e63-11e6-91f7-fbd3a0c4058a.png)

Também precisa ter FORMULARIO

![2016-08-09_18h59_41](https://cloud.githubusercontent.com/assets/5107285/17535220/a48cbdf8-5e63-11e6-989f-97a423092f51.png)

Link para o PSD
https://drive.google.com/open?id=0B7wXMgHIJOr-STJaeXlZcWgwV2M

**Comment by matheusgimenez** [comment]
A home vai ser uma página e cada item do slider será uma página filha.

**Comment by isaquemelo** [comment]
1 - A cor dos títulos e suas respectivas seções presente no slider, deverão ser selecionadas no momento de criação do mesmo. Já que a cor do background pode variar, CAUSANDO não visualização do texto. Deve ser possível a seleção de apenas duas cores [branco, e preto fosco(#2d2d2d)] para não sair do padrão do design. Esses elementos (títulos e seções) estão recebendo os valores das variáveis: $cor-txt-post e $cor-btt-hover-txt ($cor-btt-hover-txt é a cor oposta da cor do $cor-txt-post, não poderá ser selecionada pelo usuário, para evitar fuga do padrão.) @diogosp confirma isso pra mim por favor. Só assim o @matheusgimenez saberá o que fazer no back.

**Comment by diogosp** [comment]
Matheus e Isaque,
Eu gostei da percepção pra compreender o desafio de criar um menu
transparente compatível com todas as páginas do site, mas vcs
(principalmente o Matheus) acham viável que cada página tenha um seletor de
cor de menu? como ficaria isso no Customizer? acho que no máximo deveríamos
ter um seletor de cor GLOBAL pro site. que poderia ser variado mas que
refletisse pra todas as páginas ao mesmo tempo.

## 

_Diogo Soares_
Brasa Design e Tecnologia - www.brasa.art.br http://brasa.art.br/
Tel.: (11)  3042-4475

Em 24 de agosto de 2016 08:37, Isaque Melo notifications@github.com
escreveu:

**Comment by matheusgimenez** [comment]
Back-end feito:

http://dev.brasa.art.br/mb45/

Precisamos agora do @isaquemelo pra colocar um text-shadow nos textos dos sliders, a visibilidade fica ruim em alguns itens e no layout está resolvido dessa forma (com sombra).

**Comment by isaquemelo** [comment]
Correções de Front-end acima efetuada. Além disso, o problema do slider também foi corrigido.

**Comment by diogosp** [comment]
Isaque, acredito que não foi corrigido não. você pode verificar se  foi pro
DEV mesmo?

**Comment by isaquemelo** [comment]
O que você diz que não foi corrigido? As sombras foram colocadas sim nos textos em DEV. Se refere ao slider?

**Comment by diogosp** [comment]
@isaquemelo aqui alguns ajustes que a cliente pediu:
- title letter spacing, mudar para 3px ao invés de 6px;
- Remover shadow dos titulo e texto;
- Nos Botoes: tirar shadow do text
- homepage slide blowout: texto deve ser color:#000;
- deletar bolinha navegação footer (isto é, manter as bolinhas pra cada slide, só remover a bolinha correspondente ao Footer).

**Comment by diogosp** [comment]
@isaquemelo com relação aos menus transparentes. Ela disse que é pra manter assim mesmo, o menu não é pra estar visível todo o tempo. Fica assim transparente.

**Comment by isaquemelo** [comment]
Feito. Só não entendi o ponto 4.

**Comment by diogosp** [comment]
o ponto 4 ta resolvido. é o texto em preto. mas temos o seletor.

**Comment by diogosp** [comment]
@isaquemelo temos um impasse aqui. no slider BLOWOUT a fonte aparece em preto pq o fundo é mais branco. Só que na versão mobile como a imagem encurta o texto fica em cima do cabelo e aí o texto desaparece. A cliente quer que fique branco porém não temos controles de cor por versão.  Alguma saída sem precisar mudar nada? Mexer no posicionamento da imagem?

![3f7a912e-5e63-11e6-91f7-fbd3a0c4058a](https://cloud.githubusercontent.com/assets/5107285/21826409/7f62e604-d76e-11e6-9e9a-3799d52ed83e.png)

**Comment by isaquemelo** [comment]
@diogosp A unica maneira que eu pensei foi criar um custom field e nele a pessoa escolheria o alinhamento do BG. Pois se eu aplicar uma propriedade CSS será "valido para todos"(não teremos controle de quem recebe ou não)

**Comment by diogosp** [comment]
Pode fazer assim. Mas me explica melhor. Vai funcionar somente pro Mobile? E na versão desktop vai puxar full?
@isaquemelo
