### ISSUE TITLE
Page Template - Menu e Price List

### ISSUE THREAD

**Issue by diogosp** [brasadesign/mb45-theme#4]
Página com duas seções. Menu (Cardápio) e Price (Preços)
- [ ] Cor do Fundo do Menu acompanha o fundo da página
- [ ] Duas seções com edições independentes - Editor HTML comum
- [ ] Título Centralizado - seguir fontes e centralizações

![2016-08-09_19h03_58](https://cloud.githubusercontent.com/assets/5107285/17535335/4ddf6450-5e64-11e6-9904-2efb1c2dda1c.png)

Link para o PSD
https://drive.google.com/open?id=0B7wXMgHIJOr-R1lPYUEtUkhlVG8

**Comment by isaquemelo** [comment]
Observar funcionamento no Dev.

**Comment by isaquemelo** [comment]
Só para esclarecer. O "MENU" é a pagina mãe e o "PRICES" é a filha. Ou seja o "MENU" e a "PRICES" são "uma pagina só", sendo assim, não é necessário que o "MENU" esteja com a "PRICES" no header como submenu. Só é necessário o "MENU" já que é a mãe.

**Comment by diogosp** [comment]
@isaquemelo eu entendo teu argumento, mas o layout dela diz outra coisa. Vou criar um sub-menu chamado PRICES mas apontando pra MENU. Aí chama as duas OK?

**Comment by isaquemelo** [comment]
Sem problemas mano.. Agora não se esquece de apontar pro menu não viu? hehe a minha preocupação era essa
