### ISSUE TITLE
Page Template - HAIR

### ISSUE THREAD

**Issue by diogosp** [brasadesign/mb45-theme#5]
Página para os Cortes de Cabelo
LOOKS > HAIR no menu
- [ ] SLIDER com os diferentes estilos de Corte
- [ ] 5 slides
- [ ] 4 fotos e título centralizado entre as imagens
- [ ] Dúvida - se precisa de LINK pra clicar nas imagens.

![2016-08-09_19h10_33](https://cloud.githubusercontent.com/assets/5107285/17535516/6cc5f978-5e65-11e6-96b4-d9399c0da5eb.png)
![2016-08-09_19h10_51](https://cloud.githubusercontent.com/assets/5107285/17535517/6cd4ea82-5e65-11e6-831a-90b475facc71.png)
![2016-08-09_19h11_05](https://cloud.githubusercontent.com/assets/5107285/17535518/6cd6be48-5e65-11e6-90a3-b2008af027df.png)

Link para o PSD

Página no Invision
https://projects.invisionapp.com/share/7G76NWG8C#/screens/154272232

**Comment by diogosp** [comment]
@isaquemelo o slider aqui ficou diferente da Home? De onde ele está puxando cada slide se não tem página filha?

Preciso colocar todos os slides de acordo com o layout nas 3 páginas de serviço [LINK](https://github.com/brasadesign/mb45-theme/milestone/5). Você consegue criar todos os slides?

O rodapé pra estas páginas está desativado

**Comment by isaquemelo** [comment]
@diogosp Falta o backend, nessa pagina. Ela ainda está estatica. Vê isso com o @deshawn

**Comment by diogosp** [comment]
@matheusgimenez precisamos concluir esta página aqui, falta o backend

**Comment by diogosp** [comment]
@isaquemelo @matheusgimenez a dificuldade desta página aqui é que há 4 imagens de cada corte de cabelo que precisam encaixar no Mobile.

O Isaque falou em criar Filha da filha pra cada DOWN. pras imagens ficaram separadas.
Talvez dê pra fazer uma galeria de imagens destacadas (no Woo - Produto - funciona assim não?

**Comment by diogosp** [comment]
@isaquemelo deixar o BG do box preto um pouco menor na altura.

Siga a instrução do PRINT:

<img width="1280" alt="screen shot 2016-10-21 at 9 39 08 pm 2x" src="https://cloud.githubusercontent.com/assets/5107285/21826909/77677918-d770-11e6-8dae-bc3c5d3a7792.png">

**Comment by isaquemelo** [comment]
Feito.
