### ISSUE TITLE
Page Template - NAILS

### ISSUE THREAD

**Issue by diogosp** [brasadesign/mb45-theme#6]
Página dentro do menu LOOKS > NAILS
- [ ] SLIDER vertical - igual da HOME
- [ ] 5 Slides ou mais
- [ ] Títulos e Sub-titulos editáveis

![2016-08-09_19h16_37](https://cloud.githubusercontent.com/assets/5107285/17535590/e1e3df40-5e65-11e6-80dc-5b38afba978e.png)
![2016-08-09_19h16_48](https://cloud.githubusercontent.com/assets/5107285/17535591/e2070038-5e65-11e6-9137-799fdf985d00.png)

**Comment by isaquemelo** [comment]
@diogosp back-end dessa aqui tbem tá pronto. Ou seja já pode editar da mesma forma da home.
