### ISSUE TITLE
Page Template >> Braids and Updos

### ISSUE THREAD

**Issue by diogosp** [brasadesign/mb45-theme#7]
Página para 
LOOKS > Braids and UPDOS
- [ ] slider vertical
- [ ] 5 pra mais
- [ ] Imagens - títulos e subtitulos

![2016-08-09_19h18_37](https://cloud.githubusercontent.com/assets/5107285/17535679/710ddd60-5e66-11e6-9c47-5d873e4c425a.png)
![2016-08-09_19h18_50](https://cloud.githubusercontent.com/assets/5107285/17535680/71164fcc-5e66-11e6-93f4-a0c8cd16da43.png)

Link no Invision
https://projects.invisionapp.com/share/7G76NWG8C#/screens/154271633

**Comment by isaquemelo** [comment]
@matheusgimenez essa é uma copia da página NAILS.. só tem o botão a mais.

**Comment by diogosp** [comment]
@matheusgimenez @isaquemelo tem que criar este page template tb.

**Comment by isaquemelo** [comment]
Amanhã realizarei.

**Comment by isaquemelo** [comment]
Tá feito. Entretanto, ainda estático, haja vista, que ainda falta o back-end

**Comment by isaquemelo** [comment]
Back-end feito. @diogosp essa já tá dinamica. Pode editar da mesma forma da home.
