### ISSUE TITLE
Checkout >> Step 1

### ISSUE THREAD

**Issue by diogosp** [brasadesign/mb45-theme#9]
Passo 1 do Checkout - Escolha dos Serviços
- [x] Título da página com sub-titulo. Mostra o STEP que o cliente está
- [x] 4 menus dropdowns com escolha serviços etc
- [x] botão NEXT
- [x] Sem RODAPÉ

Explicação
- Campo GUEST: usuário escolhe quantos vão agendar o serviço. de 1 a 4.
- Campo de Serviço: usuário escolhe 1 serviço por guest.
- Pra isso o campo de serviço precisa aparecer pra cada Guest:

Guest 1 - Service X
Guest 2 - Service Y

Exemplo de interface que eles se basearam: http://paint-box.com/book

Layout Atualizado
https://projects.invisionapp.com/share/7G76NWG8C#/screens/155745055

![selection_003](https://cloud.githubusercontent.com/assets/5107285/19196922/c1bd09b6-8c8d-11e6-9b41-da8198737d17.png)

**Comment by matheusgimenez** [comment]
Feito o sisteminha - falta CSS, que com a ausencia do Isaque farei essa parte amanhã
